queue_rules:
  - name: duplicated default queue from Automatic queue to dev on approval (__release-pkg)
      [low]
    queue_conditions:
      - "#approved-reviews-by>=1"
      - label!=work-in-progress
      - label!=wip
      - label!=no-auto-squash-merge
      - base=dev
      - head!=next
      - -conflict
      - -draft
      - -locked
      - status-success~=^version-check\s\(.*\)$
      - status-success~=^lint\s\(.*\)$
      - status-success~=^build\s\(.*\)$
      - status-success~=^build-doc\s\(.*\)$
      - status-success~=^unit-test\s\(.*\)$
      - status-success~=^integration-test\s\(.*\)$
      - "#review-threads-unresolved=0"
      - "#approved-reviews-by>=1"
      - label!=work-in-progress
      - label!=wip
      - label!=no-auto-squash-merge
      - base=dev
      - head=__release-pkg
      - -conflict
      - -draft
      - -locked
      - status-success~=^build\s\(.*\)$
      - "#review-threads-unresolved=0"
    merge_conditions: []
    merge_method: squash
  - name: default queue
    queue_conditions:
      - "#approved-reviews-by>=1"
      - label!=work-in-progress
      - label!=wip
      - label!=no-auto-squash-merge
      - base=dev
      - head!=next
      - -conflict
      - -draft
      - -locked
      - status-success~=^version-check\s\(.*\)$
      - status-success~=^lint\s\(.*\)$
      - status-success~=^build\s\(.*\)$
      - status-success~=^build-doc\s\(.*\)$
      - status-success~=^unit-test\s\(.*\)$
      - status-success~=^integration-test\s\(.*\)$
      - "#review-threads-unresolved=0"
    merge_conditions:
      - label!=work-in-progress
      - label!=wip
      - status-success~=^build\s\(.*\)$
    merge_method: squash

pull_request_rules:
  - name: automatic approval for release package PR
    conditions:
      - author~=^ConfluxBot$
      - base=dev
      - head=__release-pkg
    actions:
      review:
        type: APPROVE
        message: Automatically approving release package PR
  - name: automatic update PR with merge
    conditions:
      - -conflict
      - -draft
      - label!=work-in-progress
      - label!=wip
      - label!=no-auto-merge-updates
      - head!=dev
      - head!=main
    actions:
      update:
  - name: Automatic queue to dev on approval (__release-pkg) [low] + Automatic queue
      to dev on approval [low]
    conditions: []
    actions:
      queue:
