pull_request_rules:
  - name: automatic approval for release package PR
    conditions:
      - author~=^ConfluxBot$
      - "base=dev"
      - "head=__release-pkg"
    actions:
      review:
        type: APPROVE
        message: Automatically approving release package PR
  - name: automatic update for PR
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # filter-out GH draft PRs
    actions:
      update:
  - name: Automatic squash to dev on approval
    conditions:
      - "#approved-reviews-by>=1"
      - label!=work-in-progress
      - label!=wip
      - "base=dev"
      - "-merged"
      - "-closed"
      - "-conflict"
      - "-merged"
      - "-draft"
      - "-locked"
      - "#check-pending=0"
      - "#review-threads-unresolved=0"
      - "#commits=1"
    actions:
      merge:
        method: squash
  - name: Automatic merge to dev on approval
    conditions:
      - "#approved-reviews-by>=1"
      - label!=work-in-progress
      - label!=wip
      - "base=dev"
      - "-merged"
      - "-closed"
      - "-conflict"
      - "-merged"
      - "-draft"
      - "-locked"
      - "#check-pending=0"
      - "#review-threads-unresolved=0"
      - "#commits>1"
    actions:
      merge:
        method: merge
