changesetBaseRefs:
  - origin/dev

compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: true

nodeLinker: node-modules

npmPublishAccess: public

preferDeferredVersions: true

unsafeHttpWhitelist:
  - localhost

yarnPath: .yarn/releases/yarn-4.4.0.cjs
