coverage:
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 1%
        base: auto
        flags:
          - unit

ignore:
  - 'packages/db'
  - 'packages/spec'
