// # db schema
/*
  Documentation about db schema

  - identity: true (default to false)
  Means there will no duplicate records of the same attribute with same value,
  eg. `:account/ethHexAddress` has the 'identity: true', so that there will only
  be one account if you run `db.createAccount({ethHexAddress: 1})` twice, cause
  they are the same account.
  https://docs.datomic.com/on-prem/schema/identity.html#unique-identities

  - value: true (default to false)
  Same as identity: true, but will throw an error if try to insert the same attribute
  twice. https://docs.datomic.com/on-prem/schema/identity.html#unique-values

  - persist: false (default to true)
  Means the attribute won't be available in the result of `SerializeToStr(db)`.
  Note that this is a custom implementation in this project.

  - ref: true/model-name (default to false)
  Means this attribute is a reference to another entity.
  When set to true, use the attribute name as the ref model name.
  When set to string, use the string as the ref model name.

  - component: true (default to false)
  Means this attribute is the representation of an entity and it's one of the
  children of the parent entity.
  Doc about component feature https://blog.datomic.com/2013/06/component-entities.html
  */
const schema = {
  // ## basic
  hdPath: {
    value: {value: true},
    name: {identity: true},
  },
  network: {
    name: {
      identity: true,
      doc: "Name of a network, used as id of network, builtin network name can't be changed, reload(reinit) the extension if network name changed",
    },
    icon: {many: true, doc: 'icon urls of this network'},
    endpoint: {
      value: true,
      doc: "RPC endpoint of a network, can't be duplicate",
    },
    type: {
      doc: "One of 'cfx'/'eth', indicating type of rpc set of this network",
    },
    hdPath: {ref: true},
    chainId: {doc: 'Network chain id, hexadecimal'},
    netId: {doc: 'Network id, decimal'},
    ticker: {
      doc: 'A object with info of the currency, eg. {name: "Ethereum", symbol: "CFX", decimals: 18}',
    },
    address: {ref: true, many: true, component: true},
    builtin: {doc: "Indicating builtin network, shouldn't be deleted"},
    scanUrl: {doc: 'Url of block chain explorer'},
    selected: {doc: 'network selected by wallet'},
    tokenList: {
      doc: 'token list of this network',
      ref: true,
    },
    balanceChecker: {doc: 'balance checker contract address'},
    token: {
      doc: 'tokens from token list, dapp, and user of this network',
      ref: true,
      many: true,
      component: true,
    },
    isMainnet: {doc: 'is mainnet network'},
    isTestnet: {doc: 'is testnet network'},
    isCustom: {doc: 'is custom network'},
  },
  /*
    vault, container of credential (address/pk/mnemonic)
    */
  vault: {
    type: {doc: 'Type of vault: pub, pk, hd'},
    data: {doc: 'Encrypted vault data'},
    ddata: {doc: 'Decrypted vault data only in memory', persist: false},
    cfxOnly: {
      doc: 'If type is pub, means this vault is only for cfx type network, if type is hd, means only generate 0x1 prefix account',
    },
  },
  accountGroup: {
    nickname: {value: true},
    vault: {ref: true, doc: 'Entity ID of vault', identity: true},
    // customHdPath: {
    //   ref: 'hdPath',
    //   doc: 'Entity ID of hd path, when set, will use this custom hd path for whatever network',
    // },
    // network: {
    //   doc: 'Network supported by this account group',
    //   ref: true,
    // },
    hidden: {doc: 'If hide this accountGroup in ui'},
    account: {ref: true, many: true, component: true},
  },
  address: {
    vault: {ref: true},
    balance: {doc: 'balance of this address'},
    index: {doc: 'Address index in hd path, starts from 0'},
    hex: {doc: 'The value of the address, not cfx hex address'},
    cfxHex: {doc: 'The value of cfx hex address'},
    base32: {doc: 'base32 addr of the right network'},
    pk: {doc: 'the private key of the address', persist: false},
    token: {
      doc: 'tokenlist of this address',
      many: true,
      ref: true,
    },
  },
  account: {
    index: {doc: 'index of account in account group'},
    nickname: {doc: 'account nickname'},
    address: {many: true, component: true, ref: true},
    hidden: {doc: 'If hide this account in ui'},
    offline: {doc: 'Offline account'},
    selected: {doc: 'selected by wallet'},
  },

  // ## dapp interaction
  site: {
    origin: {
      identity: true,
      doc: 'domain of the map, eg: https://.* or chrome-extension://.*',
    },
    name: {doc: 'site name'},
    icon: {doc: 'site icon href'},
    post: {
      persist: false,
      doc: 'the function to post message to inpage runtime',
    },
  },
  app: {
    site: {ref: true, identity: true},
    name: {doc: 'name of the app'},
    perms: {
      doc: 'authorized permissions, eg. {wallet_basic: {}, wallet_accounts: {}}',
    },
    permUpdatedAt: {doc: 'permision last updated at, generated by Date.now()'},
    account: {doc: 'authed accounts', ref: true, many: true},
    currentAccount: {ref: 'account'},
    network: {doc: 'authed network', ref: true, many: true},
    currentNetwork: {ref: 'network'},
  },
  authReq: {
    req: {doc: 'the req body of the auth req', persist: false},
    site: {ref: true, persist: false},
    app: {ref: true, persist: false},
    c: {doc: 'csp channel of the req listener', persist: false},
  },
  balance: {
    value: {doc: 'balance value in hex'},
    'address+token': {
      tuples: ['balance/address', 'balance/token'],
      identity: true,
    },
    address: {ref: true},
    token: {ref: true},
  },

  // ## utils
  unlockReq: {
    req: {persist: false},
  },

  // ## tokens
  token: {
    address: {doc: 'address, hex or base32'},
    symbol: {doc: 'token symbol'},
    decimals: {doc: 'token decimal'},
    logoURI: {doc: 'token logo image'},
    fromList: {doc: 'true when from token list'},
    fromApp: {doc: 'true when from app'},
    fromUser: {doc: 'true when from user'},
    // ... other values in TokenInfoSchema
  },
  tokenList: {
    url: {doc: 'token list url', value: true},
    name: {doc: 'token list name'},
    value: {doc: 'token list value, json data get from token list'},
    token: {
      doc: 'token of this token list',
      many: true,
      ref: true,
    },
  },
}

export default schema
