import {
  CONNECT_SITE,
  CONFIRM_ADD_SUGGESTED_TOKEN,
  REQUEST_SIGNATURE,
  DAPP_ADD_NETWORK,
  DAPP_SWITCH_NETWORK,
} from './route'
import {
  REQUEST_PERMISSIONS,
  CFX_SIGN_TYPED_DATA_V4,
  ETH_SIGN_TYPED_DATA_V4,
  WALLET_SWITCH_CONFLUX_CHAIN,
  WALLET_SWITCH_ETHEREUM_CHAIN,
  WALLET_ADD_ETHEREUM_CHAIN,
  WALLET_ADD_CONFLUX_CHAIN,
  WALLET_WATCH_ASSET,
} from './rpcMethods'
export * as RPC_METHODS from './rpcMethods'
export * as ROUTES from './route'
export const LANGUAGES = ['en', 'zh-CN']
export const ANIMATE_DURING_TIME = 300
export const PASSWORD_REG_EXP =
  /^(?=.*\d)(?=.*[a-zA-Z])[\da-zA-Z~!@#$%^&*]{8,16}$/
export const NETWORK_TYPE = {
  CFX: 'cfx',
  ETH: 'eth',
}

export const DAPP_REQUEST_ROUTES = {
  [REQUEST_PERMISSIONS]: CONNECT_SITE,
  [CFX_SIGN_TYPED_DATA_V4]: REQUEST_SIGNATURE,
  [ETH_SIGN_TYPED_DATA_V4]: REQUEST_SIGNATURE,
  [WALLET_SWITCH_CONFLUX_CHAIN]: DAPP_SWITCH_NETWORK,
  [WALLET_SWITCH_ETHEREUM_CHAIN]: DAPP_SWITCH_NETWORK,
  [WALLET_ADD_ETHEREUM_CHAIN]: DAPP_ADD_NETWORK,
  [WALLET_ADD_CONFLUX_CHAIN]: DAPP_ADD_NETWORK,
  [WALLET_WATCH_ASSET]: CONFIRM_ADD_SUGGESTED_TOKEN,
}
