import {
  CONNECT_SITE,
  CONFIRM_ADD_SUGGESTED_TOKEN,
  REQUEST_SIGNATURE,
  DAPP_ADD_NETWORK,
  DAPP_SWITCH_NETWORK,
  CONFIRM_TRANSACTION,
} from './route'
import {
  WALLET_REQUEST_PERMISSIONS,
  CFX_SIGN_TYPED_DATA_V4,
  ETH_SIGN_TYPED_DATA_V4,
  WALLET_SWITCH_CONFLUX_CHAIN,
  WALLET_SWITCH_ETHEREUM_CHAIN,
  WALLET_ADD_ETHEREUM_CHAIN,
  WALLET_ADD_CONFLUX_CHAIN,
  WALLET_WATCH_ASSET,
  CFX_SEND_TRANSACTION,
  ETH_SEND_TRANSACTION,
  PERSONAL_SIGN,
} from './rpcMethods'
export * as RPC_METHODS from './rpcMethods'
export * as ROUTES from './route'
export const LANGUAGES = []
export const ANIMATE_DURING_TIME = 300
export const PASSWORD_REG_EXP = /^(?=.*\d)(?=.*[a-zA-Z]).{8,16}$/
export const NETWORK_TYPE = {
  CFX: 'cfx',
  ETH: 'eth',
}

export const DAPP_REQUEST_ROUTES = {
  [WALLET_REQUEST_PERMISSIONS]: CONNECT_SITE,
  [CFX_SIGN_TYPED_DATA_V4]: REQUEST_SIGNATURE,
  [ETH_SIGN_TYPED_DATA_V4]: REQUEST_SIGNATURE,
  [PERSONAL_SIGN]: REQUEST_SIGNATURE,
  [WALLET_SWITCH_CONFLUX_CHAIN]: DAPP_SWITCH_NETWORK,
  [WALLET_SWITCH_ETHEREUM_CHAIN]: DAPP_SWITCH_NETWORK,
  [WALLET_ADD_ETHEREUM_CHAIN]: DAPP_ADD_NETWORK,
  [WALLET_ADD_CONFLUX_CHAIN]: DAPP_ADD_NETWORK,
  [WALLET_WATCH_ASSET]: CONFIRM_ADD_SUGGESTED_TOKEN,
  [CFX_SEND_TRANSACTION]: CONFIRM_TRANSACTION,
  [ETH_SEND_TRANSACTION]: CONFIRM_TRANSACTION,
}

export const DEFAULT_TOKEN_URL =
  'https://conflux-static.oss-cn-beijing.aliyuncs.com/fluent/icons/default-token-icon.svg'
