export const GET_ALL_ACCOUNT_GROUP = ['wallet_getAccountGroup']
export const GET_HD_ACCOUNT_GROUP = ['wallet_getAccountGroup', 'hd']
export const GET_PK_ACCOUNT_GROUP = ['wallet_getAccountGroup', 'pk']
export const GET_WALLET_STATUS = ['wallet_isLocked']
export const GET_NO_GROUP = ['wallet_zeroAccountGroup']
