export const WALLET_GET_ACCOUNT_GROUP = 'wallet_getAccountGroup'
export const WALLET_GET_PENDING_AUTH_REQUEST = 'wallet_getPendingAuthRequest'
export const WALLET_REJECT_PENDING_AUTH_REQUSET =
  'wallet_userRejectedAuthRequest'
export const WALLET_APPROVE_PENDING_AUTH_REQUEST =
  'wallet_userApprovedAuthRequest'
export const ACCOUNT_GROUP_TYPE = {
  HD: 'hd',
  PK: 'pk',
  HW: 'hw',
}
export const WALLET_IS_LOCKED = 'wallet_isLocked'
export const WALLET_GET_CURRENT_DAPP = 'wallet_getCurrentViewingApp'
export const WALLET_GET_ACCOUNT_ADDRESS_BY_NETWORK =
  'wallet_getAccountAddressByNetwork'
export const WALLET_ZERO_ACCOUNT_GROUP = 'wallet_zeroAccountGroup'
export const WALLET_METADATA_FOR_POPUP = 'wallet_metadataForPopup'
export const WALLET_GENERATE_MNEMONIC = 'wallet_generateMnemonic'
export const WALLET_IMPORT_MNEMONIC = 'wallet_importMnemonic'
export const WALLET_IMPORT_PRIVATE_KEY = 'wallet_importPrivateKey'
export const WALLET_VALIDATE_MNEMONIC = 'wallet_validateMnemonic'
export const WALLET_VALIDATE_PRIVATE_KEY = 'wallet_validatePrivateKey'
export const WALLET_CREATE_ACCOUNT = 'wallet_createAccount'
export const WALLET_UNLOCK = 'wallet_unlock'
export const LOCK = 'wallet_lock'
export const WALLET_GET_NETWORK = 'wallet_getNetwork'
export const WALLET_GET_BALANCE = 'wallet_getBalance'
export const WALLET_SET_CURRENT_NETWORK = 'wallet_setCurrentNetwork'
export const WALLET_SET_CURRENT_ACCOUNT = 'wallet_setCurrentAccount'
export const WALLET_REQUEST_PERMISSIONS = 'wallet_requestPermissions'
export const WALLET_DELETE_APP = 'wallet_deleteApp'
export const WALLET_SWITCH_CONFLUX_CHAIN = 'wallet_switchConfluxChain'
export const WALLET_SWITCH_ETHEREUM_CHAIN = 'wallet_switchEthereumChain'
export const CFX_SIGN_TYPED_DATA_V4 = 'cfx_signTypedData_v4'
export const ETH_SIGN_TYPED_DATA_V4 = 'eth_signTypedData_v4'
export const WALLET_ADD_ETHEREUM_CHAIN = 'wallet_addEthereumChain'
export const WALLET_ADD_CONFLUX_CHAIN = 'wallet_addConfluxChain'
export const WALLET_WATCH_ASSET = 'wallet_watchAsset'
export const WALLETDB_REFETCH_BALANCE = 'wallet_refetchBalance'
export const WALLET_DETECT_ADDRESS_TYPE = 'wallet_detectAddressType'
export const WALLET_VALIDATE_20TOKEN = 'wallet_validate20Token'
export const CFX_SEND_TRANSACTION = 'cfx_sendTransaction'
export const ETH_SEND_TRANSACTION = 'eth_sendTransaction'
export const WALLETDB_ACCOUNT_LIST_ASSETS = 'walletdb_accountListAssets'
export const WALLETDB_TXLIST = 'walletdb_txList'
export const PERSONAL_SIGN = 'personal_sign'
export const QUERY_ACCOUNT = 'walletdb_queryAccount'
export const QUERY_ADDRESS = 'walletdb_queryAddress'
export const QUERY_TOKEN = 'walletdb_queryToken'
export const QUERY_BALANCE = 'walletdb_queryBalance'
export const QUERY_GROUP = 'walletdb_queryGroup'
export const WALLET_EXPORT_ACCOUNT = 'wallet_exportAccount'
export const WALLET_EXPORT_ACCOUNT_GROUP = 'wallet_exportAccountGroup'
export const WALLET_GET_IMPORT_HARDWARE_WALLET_INFO =
  'wallet_getImportHardwareWalletInfo'
export const WALLET_GET_BLOCKCHAIN_EXPLORER_URL =
  'wallet_getBlockchainExplorerUrl'
export const WALLET_IMPORT_HARDWARE_WALLET_ACCOUNT_GROUP_OR_ACCOUNT =
  'wallet_importHardwareWalletAccountGroupOrAccount'
export const CFX_GET_STATUS = 'cfx_getStatus'
export const WALLET_DELETE_ACCOUNT_GROUP = 'wallet_deleteAccountGroup'
export const WALLET_UPDATE_ACCOUNT = 'wallet_updateAccount'
export const WALLET_DETECT_NETWORK_TYPE = 'wallet_detectNetworkType'
