#!/usr/bin/env bash

set -e
set -u
set -o pipefail

if ! hub pull-request \
     --message 'chore(release-pkg): release packages' \
     --base "dev" \
     --head "__release-pkg"
then
  printf '%s\n' 'Pull Request already exists'
fi