#!/usr/bin/env bash
set -euo pipefail

mkdir -p releases
SHA=${GITHUB_SHA:-na_sha}
VER=${FLUENT_VERSION:-na_version}
cd packages/browser-extension/build
zip -r ../../../releases/fluent-wallet.zip *
cd ../../../releases
mv fluent-wallet.zip "fluent-wallet-${VER}-${SHA}.zip"
cd ../