name: Comment On Release

on:
  release:
    types:
      - prereleased
      - released
      - published

jobs:
  comment-release:
    runs-on: ubuntu-latest
    steps:
      - uses: apexskier/github-release-commenter@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          comment-template: |
            New release {release_link} related to this.