name: Deploy Cross Space Dapp

on:
  pull_request:
    types:
      - closed
    branches:
      - dev

jobs:
  doploy-dapp-demo:
    if: ${{ github.event.pull_request.merged == true && github.head_ref == '__release-pkg' }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.5]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - uses: actions/cache@v2
        id: yarn-and-maven-cache # use this to check for `cache-hit` (`steps.yarn-and-maven-cache.outputs.cache-hit != 'true'`)
        with:
          path: |
            ~/.m2/repository
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            ./.shadow-cljs
          key: ${{ runner.os }}-yarn-and-maven-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('./shadow-cljs.edn') }}
          restore-keys: |
            ${{ runner.os }}-yarn-and-maven-
      - run: yarn install --immutable
      - run: yarn workspace dapp-cross-space build
      - run: cp packages/dapp-cross-space/CNAME packages/dapp-cross-space/dist/CNAME
      - name: Deploy to cross-space.fluentwallet.dev
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: "evm.fluentwallet.com"
          project: "./packages/dapp-cross-space/dist"
          login: ${{ secrets.CONFLUX_ECO_SURGE_LOGIN}}
          token: ${{ secrets.CONFLUX_ECO_SURGE_TOKEN}}
