name: Beta Release

on:
  push:
    tags:
      - 'b*'

jobs:
  pre-release:
    name: Beta Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Packaged Extension Release
        uses: thedoctor0/zip-release@master
        with:
          path: dist/
          filename: prerelease.zip
          exclusions: '*.git* *.github* .gitignore'

      - name: Create prerelease and Upload zip
        id: create_release
        uses: svenstaro/upload-release-action@2.1.0
        with:
          repo_token: ${{ secrets.TOKEN }}
          tag: ${{ github.ref }}
          release_name: ${{ github.ref }}
          file: prerelease.zip
          prerelease: true
